const books = [
    {
        title: "Harry Potter and the half-blood prince", author: "J.K. Rowling", year: 2005, genre: ["fantasy", "mystery"], rating: 4.5, description: "Harry Potter and the Half-Blood Prince is a fantasy novel written by British author J.K. Rowling. It is the sixth book in the Harry Potter series and follows Harry's sixth year at Hogwarts School of Witchcraft and Wizardry.",
        cover: "https://m.media-amazon.com/images/I/61sXBXmAWML._AC_UF1000,1000_QL80_.jpg",
        langauge: "english",
        price: 20.99,
        publisher: "Bloomsbury Publishing",
    },
    {
        title: "National Geographic Science of Everything: How Things Work in Our World",
        author: "National Geographic (Author), David Pogue (Foreword)",
        year: 2014,
        genre: ["science", "technology"],
        rating: 4.7,
        description: "National Geographic answers all the questions about how things work--the science, technology, biology, chemistry, physics, and mechanics--in an indispensible book that reveals the science behind virtually everything.",
        cover: "https://m.media-amazon.com/images/I/710Xm1RwuHL._SL1200_.jpg",
        langauge: "english",
        price: 25.99,
        publisher: "national geographic",
    },
    {
        title: "Hamlet",
        author: "William Shakespeare",
        year: 1603,
        genre: "poems",
        rating: 4.4,
        description: "A new pocket edition of William Shakespeare's classic tragic play The Tragedy of Hamlet, Prince of Denmark. Hamletis a story of family and political intrigue, revenge, and madness and remains one of Shakespeare's most enduringly popular and influential works, featuring many of his most memorable characters and verses.",
        cover: "https://m.media-amazon.com/images/I/51cjtXsg1eL._SY342_.jpg",
        langauge: "English",
        price: 7.99,
        publisher: "Independently published (16 Oct. 2021)",
    },
    {
        title: "The Hunger Games Complete Trilogy",
        author: "Suzanne Collins",
        year: 2008,
        genre: ["mystery, fiction"],
        rating:4.7,
        description: "Twelve boys and twelve girls are forced to appear in a live event called The Hunger Games.",
        cover: "https://m.media-amazon.com/images/I/61YwJ0vQPVL._SL1500_.jpg",
        langauge: "english",
        price: 15.58,
        publisher: "Scholastic; 1st edition (3 Oct. 2013)",
    },
    {
        title: "the hobbit",
        author: "J.R.R. Tolkien",
        year: 1937,
        genre: [fantasy, fiction,],
        rating: 4.8,
        description: "The Hobbit is the unforgettable story of Bilbo, a peace-loving hobbit, who embarks on a strange and magical adventure",
        cover: "https://m.media-amazon.com/images/I/81uEDUfKBZL._SY342_.jpg",
        langauge: "english",
        price: 8.27,
        publisher: "HarperCollinsChildren’sBooks",
    },
    {
        title: "12 Spanish Bedtime Stories for Kids: Short Story Books in Spanish and English",
        author: "Doodles & Safari ",
        year: 2023,
        genre: [educational,fiction,mystery],
        rating: 4.1,
        description: "Buenas Noches! Experience the joy of bedtime through twelve unique tales written in both Spanish and English. You and your child will share a variety of fun and heartwarming moments while learning important key phrases and vocabulary",
        cover: "https://m.media-amazon.com/images/I/71PP5Dl4iyL._SY342_.jpg",
        langauge: ["english", "spanish"],
        price: 4.85,
        publisher: "Independently published ",
    },
    {
        title: "Routledge Intensive Dutch Course (Routledge Intensive Language Courses)",
        author: "Gerdi Quist ",
        year: 2006,
        genre: [educational,non-fiction],
        rating: 4.3,
        description: "This intensive foundation course in Dutch is designed for those with no previous knowledge of the language. It is lively and fast-paced, providing students with a wide range of activities, and drawing on an impressive selection of source material from many different media. ",
        cover: "https://m.media-amazon.com/images/I/61VjVu23nCL._SY342_.jpg",
        langauge: "dutch",
        price: 47.99,
        publisher: " Routledge; 1st edition (",
    },
    {
        title: "Easy Portuguese Phrase Book: Over 1500 Common Phrases For Everyday Use And Travel",
        author: "Lingo Mastery,
        year: 2021,
        genre: [educational,non-fiction],
        rating: 4.2,
        description: "we at Lingo Mastery have developed Easy Portuguese Phrase Book: Over 1500 Common Phrases for Everyday Use and Travel for you, our favorite language-learner, so that you may find the best expressions for common usage in Portuguese and communicate with your Portuguese speaking friends, colleagues and client without any issue!",
        cover: "https://m.media-amazon.com/images/I/71tSHnOmGaS._SL1360_.jpg",
        langauge: "portuguese",
        price: 7.99,
        publisher: "Lingo Mastery",
    },
    {
        title: "French short stories: Nouvelles Francaises",
        author: "Richard Coward ",
        year: 1999,
        genre: [fiction,novel,mystery],
        rating: 4.5,
        description: "This is an all new version of the popular PARALLEL TEXT series, containing eight pieces of contemporary fiction in the original French and in English translation. Including stories by Bolanger, Cotnoir, Le Clezio and Germain, this volume gives afascinating insight into French culture and literature as well as providing an invaluable educational tool.",
        cover: "https://m.media-amazon.com/images/I/613GDlmp1dL._SL1200_.jpg",
        langauge: "french",
        price: 9.75,
        publisher: "Penguin; Bilingual edition ",
    },
    {
        title: "Home Before Dark: 'Clever, twisty, spine-chilling' Ruth Ware",
        author: "Riley Sager",
        year: 2021,
        genre: [horror, mystery,fiction],
        rating: 4.2,
        description: "Clever, twisty, and altogether spine-chilling. . . . [A] deliciously terrifying story. . . .You'll want to read this one after dark, ideally with the wind whistling in the eaves and a window banging somewhere just out of reach. But keep the light switch handy. You just might need it' Ruth Ware, ",
        cover: "https://m.media-amazon.com/images/I/81FjdjeZo3L._SY342_.jpg",
        langauge: "english",
        price: 6.35,
        publisher: "Hodder Paperbacks",
    },
];

